#include "pch.h"
// -*- C++ -*-
//
// generated by wxGlade 0.9.4 on Sat Oct 24 10:13:54 2020
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef MYFRAME_H
#define MYFRAME_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class MyFrame: public wxFrame {
public:
    // begin wxGlade: MyFrame::ids
    // end wxGlade

    MyFrame(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: MyFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MyFrame::attributes
    wxTextCtrl* TextEditor;
    wxStatusBar* StatusBar;
    wxMenuBar* MenuBar;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void open_setting(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // MYFRAME_H
